# Configuration du Site
title: Formid'Alpes - Formations Professionnelles
email: contact@formid-alpes.fr
description: >-
  Organisme de formation à Gap spécialisé dans les domaines techniques, l'électricité,
  le photovoltaïque, l'automatisme industriel, la sécurité et la prévention.
baseurl: "" # Laissez vide si le site est à la racine de votre domaine (https://votre-site.com/)
url: "https://formid-alpes.fr/" # Remplacez par votre URL principale
lang: fr_FR
logo: /logo-transparent-png.png

social:
  name: Formid'Alpes
  links:
    - https://www.facebook.com/FormidAlpes
    - https://www.linkedin.com/company/formid-alpes/

# Construction (Build settings)
markdown: kramdown
theme: minima # Utilisez un thème minimal par défaut ou laissez vide

# Activation des Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag # Ajout de la balise SEO
